list1 = list(range(8))
# print("This is the number of entries in list 1 \n", list1.count())
print(list1)
list1.sort()
print("\nThis is the sorted list 1:\n", list1)
list1.sort(reverse=True)
print(list1)
list2 = ["bLa", "Blu", "bq", "by", "bd"]
print(list2)
print(list2.sort())
list1.reverse()
print(list1)
print(max(list1))
print(min(list1))
print(max(list2))
print(min(list2))
print(list2.reverse())

testmatrix = [[0] * 3 for i in range(4)]
print(testmatrix)

testmatrix2 = [list(range(9))] * 5
print(testmatrix2)

columnwidth = int(
    input("\nYou can create your own matrix here. Pls enter the column width:\n")
)
rows = int(input("Great! Now enter the number of rows you would like:\n"))
usermatrix = [list(range(columnwidth))] * rows

import time

print("...")
time.sleep(1.2)
print("creating your matrix")
time.sleep(1.0)
print("10%")
time.sleep(1.2)
print("30%")
time.sleep(0.8)
print("50%")
time.sleep(0.7)
print("80%")
pillput = input("Blue pill or red pill? ")

if pillput == "red":
    print("mf mf")
else:
    print("good sleep")
    print(usermatrix)

time.sleep(0.15)
print(usermatrix)
time.sleep(0.15)
print(usermatrix)
time.sleep(0.15)
print(usermatrix)
time.sleep(0.15)
print(usermatrix)
time.sleep(0.12)
print(usermatrix)
time.sleep(0.12)
print(usermatrix)
time.sleep(0.12)
print(usermatrix)
time.sleep(0.12)
print(usermatrix)
time.sleep(0.12)
print(usermatrix)
time.sleep(0.1)
print(usermatrix)
time.sleep(0.1)
print(usermatrix)
time.sleep(0.1)
print(usermatrix)
time.sleep(0.1)
print(usermatrix)
time.sleep(0.8)
print(usermatrix)
time.sleep(0.8)
print(usermatrix)
time.sleep(0.8)
print(usermatrix)
time.sleep(0.8)
print(usermatrix)
# time.sleep(0.4)
# print(usermatrix)
# time.sleep(0.4)
# print(usermatrix)
# time.sleep(0.4)
# print(usermatrix)
# time.sleep(0.4)
# print(usermatrix)
# time.sleep(0.4)
# print(usermatrix)
# time.sleep(0.2)
# print(usermatrix)
# time.sleep(0.2)
# print(usermatrix)
# time.sleep(0.2)
# print(usermatrix)
# time.sleep(0.2)
# print(usermatrix)
# time.sleep(0.2)
# print(usermatrix)
# time.sleep(0.1)
# print(usermatrix)
# time.sleep(0.1)
# print(usermatrix)
# time.sleep(0.1)
# print(usermatrix)
# time.sleep(0.1)
# print(usermatrix)
# time.sleep(0.1)
# print(usermatrix)\/
#
# matrix1 = [[1, 2, 0], [1, 2, 0], [1, 2, 0], [1, 2, 0]]
# matrix2 = [[1, 2, 0], [1, 2, 0], [1, 2, 0], [1, 2, 0]]
# matrix3 = [[1, 2, 0], [1, 2, 0], [1, 2, 0], [1, 2, 0]]
